# Generated by Django 5.0.7 on 2024-10-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STUDENT', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
