# Generated by Django 5.0.7 on 2024-10-24 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STUDENT', '0002_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('notice_no', models.AutoField(primary_key=True, serialize=False)),
                ('notice', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
