# Generated by Django 5.0.7 on 2024-12-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STUDENT', '0008_videocontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
