# Generated by Django 5.0.7 on 2024-12-24 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STUDENT', '0009_message_file_alter_message_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('subject', models.CharField(max_length=100)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='STUDENT.student')),
            ],
        ),
    ]
